
library(tidyverse)
library(ggpubr)
library(ggrastr)

# This file is generated by taking the BED file created by filter_CCDS_introns.py
# and retrieving the intron sequences with bedtools getfasta -s -tab -nameOnly 
human_introns_all <- read_tsv('hg19.gencode.basic.v45.CCDS_introns_seqs.txt.gz', col_names = c('intron_info', 'intron_seq')) %>%
  mutate(intron_info = substr(intron_info, 1, nchar(intron_info)-3),
         intron_seq = toupper(intron_seq)) %>%
  separate(intron_info, c('transcript_id', 'ccds_id', 'gene_name', 'chrom', 'strand', 'intron_start', 'intron_end'), sep = '_', remove = T)
human_introns_all <- human_introns_all %>%
  mutate(intron_length = nchar(intron_seq)) %>%
  mutate(a_prop = str_count(intron_seq, fixed('A'))/intron_length,
         t_prop = str_count(intron_seq, fixed('T'))/intron_length,
         c_prop = str_count(intron_seq, fixed('C'))/intron_length,
         g_prop = str_count(intron_seq, fixed('G'))/intron_length) %>%
  mutate(gc_content = c_prop+g_prop,
         maximum_base_pairing = 1 - (pmax(a_prop-t_prop, 0) + pmax(c_prop-g_prop, 0) +
                                       abs(pmax(t_prop-a_prop, 0) - pmax(g_prop-c_prop, 0))))

# This data file was constructed using the NCBI Virus database/GenBank as described in the methods
# MFE data was generated with the fold_virus_introns_observed_shuffled.py script
virus_introns_all <- read_tsv('virus_introns_observed_shuffled_mfe_merged.txt')
virus_introns_all <- virus_introns_all %>%
  mutate(intron_length = nchar(intron_seq)) %>%
  mutate(a_prop = str_count(intron_seq, fixed('A'))/intron_length,
         t_prop = str_count(intron_seq, fixed('T'))/intron_length,
         c_prop = str_count(intron_seq, fixed('C'))/intron_length,
         g_prop = str_count(intron_seq, fixed('G'))/intron_length) %>%
  mutate(gc_content = c_prop+g_prop,
         maximum_base_pairing = 1 - (pmax(a_prop-t_prop, 0) + pmax(c_prop-g_prop, 0) +
                                       abs(pmax(t_prop-a_prop, 0) - pmax(g_prop-c_prop, 0))))


# Plot comparison of human and viral intron GC content
gc_pval <- round(t.test(human_introns_all$gc_content,
                        virus_introns_all$gc_content)$p.value, 2)
human_introns_all %>%
  select(gc_content) %>%
  mutate(source = 'Human') %>%
  bind_rows(virus_introns_all %>% select(gc_content) %>% mutate(source = 'Virus')) %>%
  ggplot(aes(x=source, y=100*gc_content)) +
  geom_boxplot(aes(fill=source), outlier.shape = NA) +
  geom_bracket(label = paste0('p = ', gc_pval), xmin = 'Human', xmax = 'Virus',
               y=90, tip.length = 0.02, label.size = 2) +
  labs(y='GC content (%)') +
  theme_pubr() +
  theme(axis.text.x = element_text(size=7), axis.text.y = element_text(size=6),
        axis.title.y = element_text(size=7), axis.title.x = element_blank(),
        legend.position = 'none')


# Plot comparison of human and viral intron normalized MFEs (from RNAfold)
# Human MFE data generated by fold_human_introns_observed_shuffled.py script
human_introns_5000_folded <- read_tsv('CCDS_length_5000_introns_observed_shuffled_mfe_merged.txt.gz')
human_introns_5000_folded <- human_introns_5000_folded %>%
  mutate(intron_length = nchar(intron_seq)) %>%
  mutate(observed_mfe_norm = observed_mfe/intron_length,
         shuffled_mfe_mean_norm = mean_shuffled_mfe/intron_length,
         shuffled_mfe_median_norm = median_shuffled_mfe/intron_length)
virus_introns_all <- virus_introns_all %>%
  mutate(observed_mfe_norm = observed_mfe/intron_length,
         shuffled_mfe_mean_norm = mean_shuffled_mfe/intron_length,
         shuffled_mfe_median_norm = median_shuffled_mfe/intron_length)
mfe_pval <- t.test(virus_introns_all$observed_mfe_norm,
       human_introns_5000_folded$observed_mfe_norm)$p.value
human_introns_5000_folded %>%
  select(observed_mfe_norm) %>%
  mutate(source='Human') %>%
  bind_rows(virus_introns_all %>% select(observed_mfe_norm) %>% mutate(source='Virus')) %>%
  ggplot(aes(x=source, y=-observed_mfe_norm)) +
  geom_boxplot(aes(fill=source), outlier.shape = NA) +
  coord_cartesian(ylim=c(0, 0.68)) +
  geom_bracket(label = 'p = 1.09e-09', xmin = 'Human', xmax = 'Virus',
               y=0.65, tip.length = 0.02, label.size = 2) +
  labs(y='MFE (-kcal/mol)') +
  theme_pubr() +
  theme(axis.text.x = element_text(size=7), axis.text.y = element_text(size=6),
        axis.title.y = element_text(size=7), axis.title.x = element_blank(),
        legend.position = 'none')


# Plot comparison of human and viral intron maximum base pairing metric (see Viral Intron Analysis methods section)
mbp_pval <- t.test(human_introns_all$maximum_base_pairing,
                   virus_introns_all$maximum_base_pairing)$p.value
human_introns_all %>%
  select(maximum_base_pairing) %>%
  mutate(source = 'Human') %>%
  bind_rows(virus_introns_all %>% select(maximum_base_pairing) %>% mutate(source = 'Virus')) %>%
  ggplot(aes(x=source, y=maximum_base_pairing)) +
  geom_boxplot(aes(fill=source), outlier.shape = NA) +
  coord_cartesian(ylim=c(0.6, 1.065)) +
  geom_bracket(label = 'p = 2.12e-10', xmin = 'Human', xmax = 'Virus',
               y=1.05, tip.length = 0.02, label.size = 2) +
  labs(y='Maximum base pairing') +
  theme_pubr() +
  theme(axis.text.x = element_text(size=7), axis.text.y = element_text(size=6),
        axis.title.y = element_text(size=7), axis.title.x = element_blank(),
        legend.position = 'none')


# Plot observed vs shuffled MFE for human introns
mfe_r2 <- round(cor(human_introns_5000_folded$observed_mfe_norm,
                    human_introns_5000_folded$shuffled_mfe_mean_norm)^2, 2)
ggplot(human_introns_5000_folded, aes(x=observed_mfe_norm, y=shuffled_mfe_mean_norm)) +
  rasterize(geom_point(alpha=0.25, color='#00BCDB'), dpi = 600) +
  geom_abline(intercept = 0, slope = 1) +
  annotate(geom = 'text', label = bquote(r^2 == .(mfe_r2)), x=-0.8, y=-0.1, size=2) +
  labs(x='Observed MFE', y='Mean MFE of shuffled ensemble') +
  xlim(-1,0) + ylim(-1,0) +
  theme_pubr() +
  theme(axis.title = element_text(size=7), axis.text = element_text(size=6),
        aspect.ratio = 1)

# Plot observed vs shuffled MFE for viral introns
mfe_r2 <- round(cor(virus_introns_all$observed_mfe_norm,
                    virus_introns_all$shuffled_mfe_mean_norm)^2, 2)
ggplot(virus_introns_all, aes(x=observed_mfe_norm, y=shuffled_mfe_mean_norm)) +
  rasterize(geom_point(alpha=0.25, color='#DB559F'), dpi = 600) +
  geom_abline(intercept = 0, slope = 1) +
  annotate(geom = 'text', label = bquote(r^2 == .(mfe_r2)), x=-0.8, y=-0.1, size=2) +
  labs(x='Observed MFE', y='Mean MFE of shuffled ensemble') +
  xlim(-1,0) + ylim(-1,0) +
  theme_pubr() +
  theme(axis.title = element_text(size=7), axis.text = element_text(size=6),
        aspect.ratio = 1)

# Plot distribution of difference between observed and shuffled MFE for both human and viral introns
human_virus_merged <- human_introns_5000_folded %>%
  select(observed_mfe_norm, shuffled_mfe_mean_norm) %>%
  mutate(source = 'Human') %>%
  bind_rows(select(virus_introns_all, observed_mfe_norm, shuffled_mfe_mean_norm) %>% mutate(source = 'Virus')) %>%
  mutate(observed_shuffled_mean_diff = observed_mfe_norm-shuffled_mfe_mean_norm)
mfe_diff_pval <- t.test(observed_shuffled_mean_diff ~ source, data = human_virus_merged)
ggplot(human_virus_merged, aes(x=observed_shuffled_mean_diff, fill=source)) +
  geom_density(alpha=0.5) +
  annotate(geom = 'text', label = 'p = 1.65e-06', x=-0.25, y=12, size=2) +
  labs(x='Observed MFE - Mean MFE of shuffled ensemble', y='Density') +
  scale_fill_discrete(type=c('#00BCDB', '#DB559F')) +
  theme_pubr() +
  theme(axis.title = element_text(size=7), axis.text = element_text(size=6),
        legend.position = 'bottom', legend.key.size = unit(3,'mm'),
        legend.title = element_blank(), legend.text = element_text(size=7))
